---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: naveen
    type: postgres-pod
spec:
  containers:
    - name: postgres-app
      image: postgres
      ports:
      env:
        - name: POSTGRES_PASSWORD
          value: naveenkumar
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
       - containerPort: 5432
...




