---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: naveen
    type: postgres-service
spec:
  type: clusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
   author: naveen
   type: postgres-pod
...




