---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: naveen
    type: redis-service
spec:
  type: clusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
   author: naveen
   type: redis-pod
...




