---
apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    author: naveen
    type: result-pod
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
       - containerPort: 80
...




