---
apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    author: naveen
    type: voting-pod
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
       - containerPort: 80
...




